export const faqData = [
    {
      title: "When is it advisable to hire a professional cleaning service in Montreal?",
      text: "Are you frequently confronted with dusty shelves, dingy carpets, or stubborn stains that seem to resist your cleaning efforts? You’re not alone. Many homeowners and office managers in Montreal encounter these challenges. Fortunately, there’s a solution. If you’re constantly racing against the clock, trying to maintain the level of cleanliness you desire in your Montreal home or office, it’s time to consider the benefits of hiring a professional cleaning service. Balancing work and family commitments can be challenging, leaving little time for the meticulous cleaning your space deserves.\n\nWe completely understand the difficulties of keeping your living or working space spotless when time is at a premium. That’s precisely why we offer flexible scheduling options to match your convenience. Whether you prefer cleaning while you’re away or at a time that won’t disrupt your daily routine, we’ve got you covered. We’re more than happy to arrange routine cleanings, whether it’s multiple times a month or as frequently as needed, to ensure your Montreal home or office remains in pristine condition.\n\nSo, if you’re contemplating when to enlist the assistance of a professional cleaning service in Montreal, the answer is straightforward: anytime you wish to enjoy a cleaner, more stress-free environment without sacrificing your busy schedule.\n\nCurious to learn more? Explore our house cleaning services or visit our house cleaning blog for helpful tips and advice."
    },
    {
      title: "What is the difference between a standard clean, deep clean, and move-in/move-out clean?",
      text: "Overall, the main distinction between these types of cleaning is the scope of work.\n\n\n\nOur Standard Cleaning service provides routine maintenance and care to keep your home looking tidy and fresh. It focuses on essential cleaning tasks to maintain cleanliness and hygiene. This offering is also ideal for Airbnb / short-term rental operators. Here’s what’s included in a standard cleaning service:\n\nDust and wipe all surfaces Vacuum and mop floors Clean kitchen appliances and surfaces Disinfect bathroom fixtures and mirrors Trash can emptying Address specific requests or issues Our Deep Cleaning service is designed to address areas of your home that may not receive regular attention during routine cleaning sessions. It goes beyond the basic cleaning tasks and focuses on detailed and meticulous cleaning of all areas in your living space. Here’s what’s included in our deep cleaning service:\n\nDetailed cleaning of all bedrooms and living areas Deep bathroom care and sanitization Cleaning of all kitchen surfaces and appliance surfaces Thorough vacuuming and floor sweeping Baseboard and trim wiped down Standard accessible wall and fixture cleaning Trash can emptying and disinfection We are Montreal’s leading move-in / move-out cleaning specialists. Our Move-in / Move-out Cleaning service prepares a property for new occupants or restores a property to its original condition after a tenant has moved out. We ensure that the space is clean, sanitized, and welcoming.\n\nComplete bedroom, bathroom, living space care Comprehensive floor care Cleaning of all kitchen surfaces and appliances Cabinet cleaning inside and out Wall, baseboard, trim, and fixture cleaning Blind and curtain dusting We also proudly offer post-renovation cleaning services. Whether you’ve transformed your kitchen, bathroom, or the entire property, we provide flexible and specialized services to ensure that no debris, sawdust, or dust is left behind.\n\nCurious to learn more about White Bird? Explore our house cleaning services or visit our house cleaning blog for helpful tips and advice."
    },
    {
      title: "Can I trust the caliber of White Bird Nettoyages' cleaners?",
      text: "We take great pride in the caliber of cleaning professionals we dispatch to serve you. Our team consists of seasoned and amiable cleaners, and we are highly selective in our recruitment process, admitting only the most exceptional individuals.\n\nOur commitment revolves around placing your trust and security at the forefront of our priorities. As a result, we uphold the most stringent standards for our cleaning professionals. Do not hesitate to reach out to us if you have any concerns."
    },
    {
      title: "Do you use your own cleaning supplies and equipment?",
      text: "We bring our own cleaning products and supplies to every clean, but when it comes to standard cleanings, we kindly request that clients have the essential equipment available, which should include a vacuum cleaner, a mop, and a bucket. For deep and move-in/move-out cleanings, we will provide all the necessary equipment.\n\nBringing our own products and supplies enables us to maintain a high-standard of cleanliness and efficiency. That said, if you would like us to use your own products and supplies, we’re more than happy to! Your choice.\n\nLearn more on how to be fully prepared for your professional cleaning service experience here."
    },
    {
      title: "Can I make any special requests or leave specific instructions?",
      text: "Yes, we understand you may have specific preferences when it comes to cleaning your home or office.\n\nRegardless of your cleaning style, White Bird Nettoyages offers you the flexibility to tailor your cleaning experience to your exact specifications. When you make an online booking, you have the option to provide detailed instructions for our cleaning professionals before they arrive at your home or office.\n\nWhether you have specific expectations for how a particular room or space should be cleaned or simply want to inform our cleaners about any unique circumstances, White Bird Nettoyages ensures that your home cleaning or office cleaning service is fully customizable. Please note that certain special requests may be subject to additional charges based on the nature of the request and the level of effort required."
    },
    {
      title: "What is your 100% Satisfaction Guarantee policy?",
      text: "If you have any complaints or comments, please contact us at info@thecleanpanther.ca as soon as possible.\n\nAll move-in/out and deep cleaning services include a free re-cleaning guarantee. Certain conditions apply. To be eligible and use this guarantee, you must:\n\nInform us within 48 hours of the end of the cleaning at info@thecleanpanther.ca. Provide a written explanation of the issue. Include relevant images (photos or videos) to illustrate the problem or complaint. If valid issues are raised, we will arrange a free re-cleaning of the house. We will attempt to schedule the re-cleaning within 7 days of the initial booking date. If none of these slots are accepted by you, our offer for a free re-cleaning will be canceled, along with our satisfaction guarantee. In exceptional cases, we may agree to refund up to 50% of the fees at our discretion.\n\nPlease note that for deep cleaning, move-in, and post-renovation cleanings, failure to send us complete photos or videos of the place at least 48 hours in advance of the scheduled cleaning will also void any satisfaction guarantee and potential refund."     },
    {
      title: "Do you provide cleaning tips and advice?",
      text: "Yes, you can request in advance, and we will arrange for our cleaners to provide tips and advice while cleaning your home.\n\nWe also offer a comprehensive blog that covers important topics based on the knowledge of our experienced team of cleaners! We update our residential cleaning blog and commercial cleaning blog regularly, so make sure to stay tuned."
    },
    {
      title: "Is my billing information kept safe and secure?",
      text: "Yes! We utilize SSL (Secure Sockets Layer) online security technology and other advanced cybersecurity technologies to guarantee that our website remains impervious to any compromise.\n\nAny billing information we retain is securely stored in a protected database, assuring you that it won’t be compromised in any way. Your security is our utmost concern.\n\nAt White Bird Nettoyages, we take great pride in our “no hidden fees” policy. Our pricing is completely transparent, and all charges are disclosed upfront long before you make a payment. Once you’ve booked your cleaning, you’ll have the option to create an account on our platform. This account grants you the ability to modify, reschedule, or cancel your cleaning service at any time. As a digitally-native company, we want to ensure that you have complete control over your services and can trust us our online booking platform."
    },
    {
      title: "Can I cancel my appointment?",
      text: "You can cancel your appointment at any time by accessing your account and initiating the cancellation, contacting us via phone, or sending an email.\n\nPlease note that we require a minimum of 48 hours’ notice for all cancellations. Cancellations made less than 48 hours before your appointment will result in a 50% charge. Cancellations made more than 48 hours in advance will not incur any fees.\n\nIn the event you cancel your cleaning the same day as it was supposed to happen, with no valid reason, penalty fees corresponding to 100% of the total booking amount will be charged."
    }
  ];
  